version: "3.9"
services:
  maria_db:
    image: mariadb
    container_name: maria_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cycle
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/docker/containers/mc1/db/data:/var/lib/mysql
networks:
  default:
    driver: bridge
    name: maria_db_net
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16